bucket_name_for_root_directory = "poc-cw-root-directory-bucket"
bucket_name_for_logs           = "poc-cw-logs-bucket"
ingress_cidr_blocks            = []
name_prefix                    = "poc-cw-without-vpc"
key_pair                       = "fd-emr-test"
vpc_id                         = "" # <---- Replace me
application_subnet_id          = "" # <---- Replace me
compute_subnet_id              = "" # <---- Replace me
vpce_logs_endpoint_dnsname     = "" # <---- Replace me
