branches:
  - master
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: MAJOR
          release: major
        - type: MINOR
          release: minor
        - type: PATCH
          release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'